

terminal:
  ansi: true
  silent: false
  width: 80

async:
  threadCount: -1
  timeoutSeconds: 14400

ego:
  client:
    timeout-seconds:
      call: 10
      connect: 10
      read: 10
      write: 10
    retry:
      max-attempts: 5
      initial-seconds: 2
      max-seconds: 256
      multiplier: 2.0

compose:
  network: dms-swarm-network

docker:
  #NOTE: Indicates if this application is RUNNING-AS a docker container on the host machine. If false, then it is running on bare-metal on the host machine. This is mostly to help resolve the what URLs the DMS uses to interact with the services. If its RUNNING-AS a docker container, then it will be in the dms swarm network, and so it can use the service names as the domain in the urls, since docker will resolve the IP. If its not, then the url for the service will be used.
  run-as: false
  # If blank, will use the system default docker daemon. Useful for using a remote docker daemon.
  host: ""
